// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.HealthResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness probe (checks the database)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReadyResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.ReadyResponse"
                        }
                    }
                }
            }
        },
        "/v1/ag-ui/run": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Accepts an AG-UI ` + "`" + `RunAgentInput` + "`" + ` and streams the turn back as AG-UI protocol Server-Sent Events: ` + "`" + `RUN_STARTED` + "`" + `, ` + "`" + `TEXT_MESSAGE_START` + "`" + ` / ` + "`" + `TEXT_MESSAGE_CONTENT` + "`" + ` / ` + "`" + `TEXT_MESSAGE_END` + "`" + `, ` + "`" + `TOOL_CALL_START` + "`" + ` / ` + "`" + `TOOL_CALL_ARGS` + "`" + ` / ` + "`" + `TOOL_CALL_END` + "`" + ` / ` + "`" + `TOOL_CALL_RESULT` + "`" + `, then ` + "`" + `RUN_FINISHED` + "`" + ` (or ` + "`" + `RUN_ERROR` + "`" + `). Each frame is a ` + "`" + `data:` + "`" + ` line whose JSON carries a ` + "`" + `type` + "`" + ` field.\n` + "`" + `threadId` + "`" + ` maps to a bepilot session: pass an existing session id to continue a conversation, or leave it empty to start a new one (the new id is returned in ` + "`" + `RUN_STARTED.threadId` + "`" + ` — persist it for the next turn). Only the last user message drives the turn; history is loaded server-side. ` + "`" + `state` + "`" + ` and ` + "`" + `context` + "`" + ` are folded into the system prompt for this turn. ` + "`" + `tools` + "`" + ` are bound as client-executed tools: the agent may call one, but bepilot only emits the ` + "`" + `TOOL_CALL_*` + "`" + ` frames and ends the run — the client must execute the tool and send the result back as a ` + "`" + `tool` + "`" + ` message on the next run. ` + "`" + `forwardedProps` + "`" + ` is accepted but has no defined effect. A request whose ` + "`" + `messages` + "`" + ` carries no user turn is treated as a history replay for an existing ` + "`" + `threadId` + "`" + ` (CopilotKit issues this when a thread becomes the active one in the UI): the response is ` + "`" + `RUN_STARTED` + "`" + ` + ` + "`" + `MESSAGES_SNAPSHOT` + "`" + ` (the session's persisted messages) + ` + "`" + `RUN_FINISHED` + "`" + `, with no new turn run or saved. Such a request naming an empty or unknown ` + "`" + `threadId` + "`" + ` is a 400, since there is nothing to replay.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "AG-UI"
                ],
                "summary": "Run an agent turn (AG-UI protocol)",
                "parameters": [
                    {
                        "description": "AG-UI RunAgentInput",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AGUIRunAgentInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "AG-UI protocol SSE event stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mcp/servers": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MCP"
                ],
                "summary": "List attached MCP servers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MCPServerListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MCP"
                ],
                "summary": "Attach or update an MCP server",
                "parameters": [
                    {
                        "description": "MCP server connection",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MCPServerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MCPServerView"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mcp/servers/{name}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MCP"
                ],
                "summary": "Detach an API-registered MCP server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/messages": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Runs one agent turn. With ` + "`" + `stream: true` + "`" + ` (or ` + "`" + `Accept: text/event-stream` + "`" + `) the response is Server-Sent Events using Anthropic frame types (` + "`" + `message_start` + "`" + `, ` + "`" + `content_block_start` + "`" + `, ` + "`" + `content_block_delta` + "`" + `, ` + "`" + `content_block_stop` + "`" + `, ` + "`" + `message_delta` + "`" + `, ` + "`" + `message_stop` + "`" + `, ` + "`" + `ping` + "`" + `, ` + "`" + `error` + "`" + `) plus the extension events ` + "`" + `tool_execution_start` + "`" + ` / ` + "`" + `tool_execution_stop` + "`" + `. ` + "`" + `message_start.message.session_id` + "`" + ` is a bepilot extension carrying the session the turn was persisted under — capture it (when ` + "`" + `metadata.session_id` + "`" + ` was omitted, a new session is created) and pass it back as ` + "`" + `metadata.session_id` + "`" + ` on the next call to continue the conversation. Otherwise a single JSON message is returned, whose ` + "`" + `session` + "`" + ` field carries the same information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/event-stream"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Create a message (streaming or buffered)",
                "parameters": [
                    {
                        "description": "Message request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MessagesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sessions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "List the authenticated user's sessions",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 30,
                        "description": "Page size (1-100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Opaque cursor from a previous response's next_cursor",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SessionList"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Create a session explicitly",
                "parameters": [
                    {
                        "description": "Session fields",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SessionBrief"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sessions/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Get a session with its reconstructed transcript",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Session id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SessionDetail"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Soft-delete a session",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Session id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Update a session's title or metadata",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Session id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SessionBrief"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sessions/{id}/messages": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "List a session's messages",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Session id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Return messages with seq greater than this",
                        "name": "after_seq",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 200,
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/skills": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Skills"
                ],
                "summary": "List skills and their status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SkillListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/skills/sync": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Skills"
                ],
                "summary": "Rescan the skills directory and reconcile the database",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SkillSyncResult"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AGUIContextItem": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "dto.AGUIMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "description": "user | assistant | tool | system | developer",
                    "type": "string"
                },
                "toolCallId": {
                    "type": "string"
                }
            }
        },
        "dto.AGUIRunAgentInput": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AGUIContextItem"
                    }
                },
                "forwardedProps": {
                    "type": "object"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AGUIMessage"
                    }
                },
                "runId": {
                    "type": "string"
                },
                "state": {
                    "type": "object"
                },
                "threadId": {
                    "type": "string"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AGUIToolDefinition"
                    }
                }
            }
        },
        "dto.AGUIToolDefinition": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object"
                }
            }
        },
        "dto.CreateSessionRequest": {
            "type": "object",
            "properties": {
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "model": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "system": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.DeleteResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "message": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        }
                    }
                },
                "type": {
                    "description": "\"error\"",
                    "type": "string"
                }
            }
        },
        "dto.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "dto.InputMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "string, or an array of content blocks",
                    "type": "object"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "dto.MCPServerListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.MCPServerView"
                    }
                }
            }
        },
        "dto.MCPServerRequest": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "command": {
                    "description": "stdio",
                    "type": "string"
                },
                "env": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "tool_allowlist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "transport": {
                    "description": "stdio | sse | streamable_http",
                    "type": "string"
                },
                "url": {
                    "description": "sse | streamable_http",
                    "type": "string"
                }
            }
        },
        "dto.MCPServerView": {
            "type": "object",
            "properties": {
                "connected_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "description": "file | api",
                    "type": "string"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "transport": {
                    "type": "string"
                }
            }
        },
        "dto.MessageListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TranscriptMessage"
                    }
                }
            }
        },
        "dto.MessageResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OutputBlock"
                    }
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "role": {
                    "description": "\"assistant\"",
                    "type": "string"
                },
                "session": {
                    "description": "bepilot extension",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.SessionBrief"
                        }
                    ]
                },
                "stop_reason": {
                    "type": "string"
                },
                "stop_sequence": {
                    "type": "string"
                },
                "type": {
                    "description": "\"message\"",
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/dto.Usage"
                }
            }
        },
        "dto.MessagesRequest": {
            "type": "object",
            "properties": {
                "history_token_budget": {
                    "description": "HistoryTokenBudget (bepilot extension) caps the approximate number of\ntokens of conversation history sent to the model this turn. Oldest\nmessages are dropped first; the latest user message is always kept, even\nif it alone exceeds the budget. 0 or omitted uses the server default\n(agent.history_token_budget); a negative value is rejected.",
                    "type": "integer",
                    "example": 24000
                },
                "max_tokens": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.InputMessage"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/dto.Metadata"
                },
                "model": {
                    "type": "string"
                },
                "provider": {
                    "description": "bepilot extension",
                    "type": "string"
                },
                "stream": {
                    "type": "boolean"
                },
                "system": {
                    "description": "string, or [{\"type\":\"text\",\"text\":\"...\"}]",
                    "type": "object"
                },
                "temperature": {
                    "type": "number"
                }
            }
        },
        "dto.Metadata": {
            "type": "object",
            "properties": {
                "session_id": {
                    "description": "bepilot extension",
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.OutputBlock": {
            "type": "object",
            "properties": {
                "content": {},
                "id": {
                    "type": "string"
                },
                "input": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "is_error": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "thinking": {
                    "type": "string"
                },
                "tool_use_id": {
                    "type": "string"
                },
                "type": {
                    "description": "text | tool_use | tool_result | thinking",
                    "type": "string"
                }
            }
        },
        "dto.ReadyResponse": {
            "type": "object",
            "properties": {
                "default_model": {
                    "type": "string"
                },
                "default_provider": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "providers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "ready"
                }
            }
        },
        "dto.SessionBrief": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "model": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.SessionDetail": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TranscriptMessage"
                    }
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "model": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.SessionList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SessionBrief"
                    }
                },
                "has_more": {
                    "type": "boolean"
                },
                "next_cursor": {
                    "type": "string"
                }
            }
        },
        "dto.SkillListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SkillView"
                    }
                }
            }
        },
        "dto.SkillSyncResult": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "integer"
                },
                "discovered": {
                    "type": "integer"
                },
                "embedded": {
                    "type": "integer"
                },
                "slugs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.SkillView": {
            "type": "object",
            "properties": {
                "allowed_tools": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "has_embedding": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "dto.TranscriptMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OutputBlock"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "seq": {
                    "type": "integer"
                },
                "stop_reason": {
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/dto.Usage"
                }
            }
        },
        "dto.UpdateSessionRequest": {
            "type": "object",
            "properties": {
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.Usage": {
            "type": "object",
            "properties": {
                "input_tokens": {
                    "type": "integer"
                },
                "output_tokens": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "An API key issued by ` + "`" + `cmd/seed` + "`" + `. ` + "`" + `Authorization: Bearer \u003ckey\u003e` + "`" + ` is also accepted.",
            "type": "apiKey",
            "name": "x-api-key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "bepilot API",
	Description:      "A streaming AI agent backend. `/v1/messages` mirrors the Anthropic Messages API (with additive `provider` and `metadata.session_id` fields); the `/v1/sessions` endpoints manage conversations and let you list a user's chats and replay transcripts.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
